### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Morse/Metadata](https://hosted.weblate.org/projects/morse/metadata/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
@comradekingu, do you know if F-Droid supports [yewtu.be](https://yewtu.be/) / [Invidious](https://github.com/iv-org/invidious)?

**Comment by comradekingu** [comment]
@comradekingu In what capacity?

**Comment by CrazyMarvin** [comment]
> @comradekingu In what capacity?

So that the video gets shown in the F-Droid Android client.
Maybe @IzzySoft or @jugendhacker know about that.

**Comment by IzzySoft** [comment]
idk. AFAIK the client doesn't support `video.txt` (from Fastlane or Triple-T) yet, nor have I seen any app with a video yet in the client. That doesn't stop you from using `video.txt` of course.

**Comment by CrazyMarvin** [comment]
> idk. AFAIK the client doesn't support `video.txt` (from Fastlane or Triple-T) yet, nor have I seen any app with a video yet in the client. That doesn't stop you from using `video.txt` of course.

Alright, thanks for the answer @IzzySoft. 😘

**Comment by CrazyMarvin** [comment]
Oh wait, I just found it. The link to the video is a bit hidden.

videotxtfastlane

**Comment by IzzySoft** [comment]
Ah! Good to know!

**Pull request merged**
