### PR TITLE
Full changelog reworked

### PR DESCRIPTION
**Pull request by comradekingu**
@CrazyMarvin
What are "special characters"?

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
I am not really sure about the "special characters". Maybe the writer was thinking of Ä, Ü, Ñ, Á and so on? You may leave that out in the reworked description if you like.

**Comment by CrazyMarvin** [comment]
I will merge this now but maybe you find time to review my ideas for changes next month, @comradekingu?

**Comment by comradekingu** [comment]
@CrazyMarvin I don't know where to find those, but sure.
Tag me in. https://www.yewtu.be/watch?v=ebjXsc0UjdQ

**Comment by CrazyMarvin** [comment]
Thanks, @comradekingu.
Basically it is just one idea and not multiple but those lines may create high expectations that we may not be able to meet. Shall we soften the statement a little?

> If you have problems using the app, please write an e-mail or open an issue on GitHub.
Responses are most often immediate, and bugs are fixed as soon as possible. 

review

**Comment by comradekingu** [comment]
@crazyMarvin "Often" doesn't mean always, and "as soon as possible" allows for every possible necessary delay.
It communicates enthusiasm to not only get but also do something about bug-reports. Win-win.

**Comment by CrazyMarvin** [comment]
Alright, then we keep it that way. You convinced me. 😉

**Pull request merged**
